### ISSUE TITLE
Unnexpected behavior when dataframe contains date columns

### ISSUE THREAD

**Issue by dfalbel** [ctlente/doctr#10]
Minimal example:

```
library(doctr)
library(lubridate)

mtcars$date <- ymd("2016-01-01") + months(1:nrow(mtcars))
e <- examine(mtcars)
```

**Comment by dfalbel** [comment]
Problema está nessa linha da função `examine_`:

```
 X[[i]] <- switch(
      class(X[[i]]$data),
      numeric = suppressWarnings(profile_num(X[[i]])),
      integer = suppressWarnings(profile_num(X[[i]])),
      character = suppressWarnings(profile_txt(X[[i]])),
      factor = suppressWarnings(profile_fct(X[[i]]))
    )
```

Ele não faz nada para as datas e retorna NULL. NULL apaga a linha da lista, dando problema no `for`.
O ideal seria ou fazer uma cópia do X para ir sobreescrevendo, ou ter sempre um método default para quando a classe não for prevista.

**Comment by ctlente** [comment]
Now unsuported types default to character
